// Broad set of business / service categories for the workspace "type" field.
// Searchable; covers trades & home services, automotive, health, food,
// retail, professional, tech, creative, and more.
export const BUSINESS_TYPES: string[] = [
  // Home & repair services
  "General Repair",
  "Appliance Repair",
  "Electronics Repair",
  "Phone & Computer Repair",
  "Handyman Services",
  "Plumbing",
  "Electrical Services",
  "HVAC / Heating & Cooling",
  "Carpentry",
  "Painting",
  "Roofing",
  "Flooring",
  "Locksmith",
  "Pest Control",
  "Cleaning Services",
  "Landscaping & Lawn Care",
  "Pool & Spa Services",
  "Moving & Storage",
  "Home Renovation",
  "Interior Design",
  // Automotive
  "Auto Repair & Mechanic",
  "Auto Body & Paint",
  "Car Wash & Detailing",
  "Tire Services",
  "Car Dealership",
  "Towing & Roadside Assistance",
  // Construction & trades
  "General Contracting",
  "Construction",
  "Architecture",
  "Civil Engineering",
  "Welding & Fabrication",
  "Masonry",
  // Health & wellness
  "Medical Practice / Clinic",
  "Dental",
  "Mental Health & Therapy",
  "Physical Therapy",
  "Chiropractic",
  "Veterinary",
  "Pharmacy",
  "Optometry",
  "Home Healthcare",
  "Fitness & Personal Training",
  "Yoga & Pilates Studio",
  "Spa & Massage",
  // Beauty & personal care
  "Hair Salon & Barber",
  "Nail Salon",
  "Beauty & Cosmetics",
  "Tattoo & Piercing",
  // Food & hospitality
  "Restaurant",
  "Café & Coffee Shop",
  "Bakery",
  "Catering",
  "Food Truck",
  "Bar & Nightlife",
  "Hotel & Hospitality",
  "Event Planning",
  "Travel & Tourism",
  // Retail & e-commerce
  "Retail Store",
  "E-commerce",
  "Grocery & Convenience",
  "Clothing & Apparel",
  "Jewelry",
  "Furniture & Home Goods",
  "Florist",
  "Pet Store & Grooming",
  // Professional services
  "Accounting & Bookkeeping",
  "Legal Services",
  "Consulting",
  "Marketing & Advertising",
  "Public Relations",
  "Human Resources & Staffing",
  "Insurance",
  "Financial Services",
  "Real Estate",
  "Property Management",
  "Notary & Document Services",
  // Technology
  "Software Development",
  "IT Services & Support",
  "Web Design & Development",
  "Cybersecurity",
  "SaaS / Software Product",
  "Data & Analytics",
  "Artificial Intelligence",
  "Telecommunications",
  // Creative & media
  "Graphic Design",
  "Photography",
  "Videography & Film",
  "Music & Audio",
  "Content Creation",
  "Printing & Signage",
  "Publishing",
  // Education
  "Education & Tutoring",
  "Childcare & Daycare",
  "Coaching & Training",
  "Online Courses",
  // Logistics & industrial
  "Logistics & Shipping",
  "Delivery & Courier",
  "Warehousing",
  "Manufacturing",
  "Wholesale & Distribution",
  "Agriculture & Farming",
  "Energy & Utilities",
  // Other
  "Nonprofit & NGO",
  "Government & Public Sector",
  "Security Services",
  "Recruitment Agency",
  "Other",
];

export const COMPANY_SIZES = [
  "Just me",
  "2–10",
  "11–50",
  "51–200",
  "201–500",
  "501–1000",
  "1000+",
];
